import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/NavigationComponents/Navbar";
import Providers from "@/Providers/Providers";
import MainFooter from "@/components/Footer/MainFooter";
import MobileNavbar from "@/components/NavigationComponents/MobileNavbar";

export const metadata: Metadata = {
  title: "Print Plus",
  description: "Generated by create next app",
  icons: {
    icon: "/notextLogo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="font-inter overflow-hidden-x-hidden"
      >
        <Providers>
          {/* Wrap with Providers */}
          <Navbar />
          <MobileNavbar />
          {children}
          <MainFooter />
        </Providers>
      </body>
    </html>
  );
}
