import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/NavigationComponents/Navbar";
import MainFooter from "@/components/Footer/MainFooter";
import MobileNavbar from "@/components/NavigationComponents/MobileNavbar";
import Providers from "@/Providers/Providers";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing, Locale } from "@/i18n/routing";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Print Plus",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

// Define static params for the [locale] segment
export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}) {
  // Safely extract locale from params
  const { locale } = await params;

  // Validate the locale and handle errors properly
  if (!locale || !routing.locales.includes(locale)) {
    notFound();
  }

  // Fetch translations for the given locale
  const messages = await getMessages({ locale });

  // Set text direction based on locale
  const direction = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={direction}>
      <body suppressHydrationWarning className="font-rubik overflow-x-hidden bg-white">
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <Navbar />
            <MobileNavbar />
            {children}
            <MainFooter />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
