export const products = [
    // Similar Products (5 items)
    {
      id: 1,
      category: "similar",
      mainFileId: 1,
      alt: "Similar Product 1",
      title: "Similar Product 1",
      price: " 100 ",
      newBadge: true,
    },
    {
      id: 2,
      category: "similar",
      mainFileId: 1,
      alt: "Similar Product 2",
      title: "Similar Product 2",
      price: " 150 ",
      saleBadge: true,
      saleAmount: "20% OFF",
    },
    {
      id: 3,
      category: "similar",
      mainFileId: 1,
      alt: "Similar Product 3",
      title: "Similar Product 3",
      price: " 200 ",
    },
    {
      id: 4,
      category: "similar",
      mainFileId: 1,
      alt: "Similar Product 4",
      title: "Similar Product 4",
      price: " 250 ",
      newBadge: true,
    },
    {
      id: 5,
      category: "similar",
      mainFileId: 1,
      alt: "Similar Product 5",
      title: "Similar Product 5",
      price: " 300 ",
      saleBadge: true,
      saleAmount: "15% OFF",
    },
  
    // Recommended Products (5 items)
    {
      id: 6,
      category: "recommendation",
      mainFileId: 1,
      alt: "Recommended Product 1",
      title: "Recommended Product 1",
      price: " 350 ",
    },
    {
      id: 7,
      category: "recommendation",
      mainFileId: 1,
      alt: "Recommended Product 2",
      title: "Recommended Product 2",
      price: " 400 ",
      newBadge: true,
    },
    {
      id: 8,
      category: "recommendation",
      mainFileId: 1,
      alt: "Recommended Product 3",
      title: "Recommended Product 3",
      price: " 450 ",
    },
    {
      id: 9,
      category: "recommendation",
      mainFileId: 1,
      alt: "Recommended Product 4",
      title: "Recommended Product 4",
      price: " 500 ",
      saleBadge: true,
      saleAmount: "10% OFF",
    },
    {
      id: 10,
      category: "recommendation",
      mainFileId: 1,
      alt: "Recommended Product 5",
      title: "Recommended Product 5",
      price: " 550 ",
    },
  ];